### PR TITLE
Lab update, middleware logic fix

### PR DESCRIPTION
**Pull request by bkendall**
Couple things:
- Change from `mocha` to `lab`. Yay!
- Fix how middleware holds data. The previous way was good for rapid development, but now the data can be in memory in the middleware

### CODE REVIEW

**Comment by tjmehta** [comment]
merge conflict

**Comment by bkendall** [comment]
@tjmehta rebased. I thought I caught mine up, but I guess not...

**Comment by cflynn07** [comment]
@tjmehta :)

**Comment by cflynn07** [comment]
^ @bkendall commenting as me

**Pull request merged**
