### PR TITLE
HTTPS Test

### PR DESCRIPTION
**Pull request by bkendall**
adding some test certs and an https test to ensure that the exposed docker-mock app can be used as an https server.

updating some dependencies as well while I'm at it

### CODE REVIEW

**Comment by cflynn07** [comment]
LGTM

**Comment by anandkumarpatel** [comment]
LGTM too but first lets ensure things dependent on this don't break

**Comment by bkendall** [comment]
You don't use https by default, so nothing should break with these changes. This is simply exposing and demonstrating the capability of docker mock to use https.

**Comment by bkendall** [comment]
updated this branch to only have the HTTPS tests

**Pull request merged**
