### PR TITLE
Handle name when creating a container and returning list of containers

### PR DESCRIPTION
**Pull request by doganyazar**
I just wanted to add functionality to get container's name from /containers/create api. 
I do not know why but Docker api returns each container's name in "Names" field when listing containers via /containers/json?all=1
(https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#list-containers)

### CODE REVIEW

**Comment by bkendall** [comment]
nice! could you create tests for these new bits of functionality?

**Comment by doganyazar** [comment]
Yeah I should have done that :) I will definitely do that in a couple of days when I am done with my current task.

**Comment by doganyazar** [comment]
Ok I have just added a check to make sure same container name cannot be used. And added test for it and also for the original Names field. 
Not sure why the coverage failed.

**Comment by cflynn07** [comment]
@doganyazar looks like your changes dropped the coverage levels below our minimum thresholds.

From `npm run coverage`
```
ERROR: Coverage for statements (81.09%) does not meet global threshold (82%)
ERROR: Coverage for lines (80.9%) does not meet global threshold (82%)
ERROR: Coverage for functions (83.33%) does not meet global threshold (87%)
```

**Comment by bkendall** [comment]
@doganyazar the `coverage` is run strictly on the `test/models` and `test/utils` folders. You need to add unit tests for `ConflictError` at minimum. I can take a closer look later today.

**Comment by doganyazar** [comment]
Coverage seems fine now :) Do you think we can merge this guys?

**Comment by cflynn07** [comment]
Thanks @doganyazar !

**Comment by cflynn07** [comment]
Just going to wait until @bkendall has a chance to review this

**Comment by bkendall** [comment]
this looks good, @doganyazar. thanks for the tests.

**Pull request merged**
